frenck/spook

hacs.json
I believe that county is not necessary here
=> Remove country from hacs.json

custom_components/spook/repairs/automation_unknown_entity_references.py, custom_components/spook/repairs/script_unknown_entity_references.py
Just a little cleanup, this could  be done simpler. Not sure how I got to the previous solution :D
=> Cleanup missing entity detection a little

README.md, custom_components/spook/sensor.py
Nice to be able to retire my old automations for counting entities by type now that Spook is here, but I noticed that a count of scripts wasn't included.
Now it is!
#overcompensation
=> Adds scripts to the specific entities counted.

custom_components/spook/repairs/__init__.py
=> Let Home Assistant accept this as repair platform

custom_components/spook/repairs/obsolete_platform_yaml_config.py, custom_components/spook/translations/en.json
Adds a repair for known removed platform configurations.
=> Add repair: Find known old platform configuration

custom_components/spook/services/__init__.py
Codesmell fix, detected by Sonarcloud
=> Remove unneeded return statement

custom_components/spook/services.yaml
=> Fix statistics_id -> statistic_id in service description

README.md, custom_components/spook/services.yaml, custom_components/spook/services/homeassistant_create_area.py
Service to create new areas on the fly
=> Add service: Create area

README.md, custom_components/spook/services.yaml, custom_components/spook/services/homeassistant_add_device_to_area.py
Adds a service to add a device to an area
=> Add service: Add device to area

README.md, custom_components/spook/services.yaml, custom_components/spook/services/homeassistant_remove_device_from_area.py
=> Add service: Remove device from area

README.md, custom_components/spook/services.yaml, custom_components/spook/services/homeassistant_add_entity_to_area.py
=> Add service: Add entity to area

README.md, custom_components/spook/services.yaml, custom_components/spook/services/homeassistant_remove_entity_from_area.py
=> Add service: Remove entity to area

README.md, custom_components/spook/services.yaml, custom_components/spook/services/homeassistant_add_alias_to_area.py
=> Add service: Add alias to area

README.md, custom_components/spook/services.yaml, custom_components/spook/services/homeassistant_remove_alias_from_area.py
=> Add service: Remove alias from area

README.md, custom_components/spook/services.yaml, custom_components/spook/services/homeassistant_set_area_aliases.py
Replaces/sets all aliases for an area at once.
=> Add service: Set aliases for an area

custom_components/spook/services/input_number_decrement.py, custom_components/spook/services/input_number_increment.py
=> Fix input number increment/decrement steps

custom_components/spook/translations/fr.json
=> Add french translations

custom_components/spook/repairs/automation_unknown_entity_references.py, custom_components/spook/repairs/script_unknown_entity_references.py
=> Ignore persistent_notification entities when detecting unused entities

custom_components/spook/translations/it.json
=> Add Italian translations

custom_components/spook/services/recorder_import_statistics.py
=> Fix statistics import service to accept None for last_rest

.github/dependabot.yml, README.md, renovate.json, sonar-project.properties
=> Add SonarCloud badge & Renovate

README.md
Not because anyone reads it... 🤷
=> Add docs for switch_as_x repair

hacs.json
=> Bump min required Home Assistant to 2023.4.0

custom_components/spook/translations/pt-BR.json
Update translations for pt-BR after #124
=> Update translations for pt-BR after #124

custom_components/spook/repairs/__init__.py
=> Prevent repair inspections to run during shutdown

custom_components/spook/repairs/obsolete_integration_yaml_config.py
Ref: https://github.com/home-assistant/core/pull/93392
=> Add samsungtv as known obsolete YAML config

custom_components/spook/manifest.json, custom_components/spook/repairs/lovelace_unknown_entity_references.py, custom_components/spook/translations/en.json
This PR adds support for finding unused entities on Home Assistant Dashboards
=> Add repair: Find unknown entities on dashboards

custom_components/spook/repairs/obsolete_integration_yaml_config.py
=> Add rainbird as knonwn obsolete YAML config

custom_components/spook/translations/fr.json
=> Update french translations

custom_components/spook/repairs/lovelace_unknown_entity_references.py
=> Fix repairs of default dashboard

custom_components/spook/repairs/lovelace_unknown_entity_references.py
=> Make Lovelace repair more resilient against configuration variations

custom_components/spook/repairs/lovelace_unknown_entity_references.py
=> Fix repairs of dashboards case where service target is a template

custom_components/spook/repairs/automation_unknown_area_references.py, custom_components/spook/repairs/automation_unknown_device_references.py, custom_components/spook/repairs/script_unknown_area_references.py, custom_components/spook/repairs/script_unknown_device_references.py
=> Handle templates found in referenced areas/devices

custom_components/spook/translations/de.json, custom_components/spook/translations/en.json, custom_components/spook/translations/fr.json, custom_components/spook/translations/it.json, custom_components/spook/translations/pt-BR.json
=> Remove unused translations

custom_components/spook/repairs/automation_unknown_area_references.py
=> Fix automation has no attribute script

custom_components/spook/repairs/script_unknown_device_references.py
=> Fix script has no attribute referenced_devices

custom_components/spook/repairs/lovelace_unknown_entity_references.py
=> Gracefully handle unexpected action configuration format

custom_components/spook/repairs/lovelace_unknown_entity_references.py
=> Gracefully handle unexpected config types

custom_components/spook/translations/nl.json
As I am Dutch, I should be able to provide Dutch translations at least 🇳🇱
Spook now speaks Dutch.
=> Spook speaks Dutch

custom_components/spook/translations/es.json
=> ¡Spook ahora habla español también

README.md, custom_components/spook/ectoplasms/homeassistant/sensor.py, custom_components/spook/translations/de.json, custom_components/spook/translations/en.json, custom_components/spook/translations/es.json, custom_components/spook/translations/nl.json
As requested here: <https://github.com/frenck/spook/discussions/75>
=> Add persistent notification sensor

README.md, custom_components/spook/button.py, custom_components/spook/const.py, custom_components/spook/ectoplasms/homeassistant/button.py, custom_components/spook/translations/de.json, custom_components/spook/translations/en.json, custom_components/spook/translations/es.json, custom_components/spook/translations/nl.json
Add button platform, including some buttons to restart or reload Home Assistant.
=> Add buttons entities for restarting or reloading Home Assistant

custom_components/spook/ectoplasms/number/services/min.py
=> Fix number.min service

README.md, custom_components/spook/translations/LICENSE.md
Add license more fitting for translations, add Weblate as the provider to translate on.
=> Add CC0 license on the translations provided by Spook

.github/workflows/black.yaml, .github/workflows/pylint.yaml, .github/workflows/ruff.yaml, hacs.json, poetry.lock, pyproject.toml, sonar-project.properties
=> Bump Home Assistant to 2023.8.1 (set minimum to 2023.8.0)

.github/workflows/release.yaml
=> Sign Spook release package

README.md
=> Put back translations into the README

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
=> Add issue form

.github/ISSUE_TEMPLATE/bug_report.yml
=> Improvements to the issue template

documentation/installation.md
=> Fix missing space

documentation/index.md
=> Add social description to index

documentation/installation.md, documentation/myst.yml
Small tweaks to the installation procedure
- Remove a note block
- Remove figure annotations
- Make sure location pointing happens at the start of a sentence
Good :)
=> Small tweaks to installation procedure

documentation/services.md
=> Typo "Uhnide" -> "Unhide"

README.md, documentation/areas.md, documentation/devices.md, documentation/features.md, documentation/installation.md, documentation/integrations.md, documentation/myst.yml
This PR collects several documentation tweaks and improvements.
Well, it is nice :)
Opening up my eyes and look at the darn thing :)
=> Collection of documentation improvements

.github/workflows/release.yaml
Don't upload sigstore signatures, as that currently causes issues with HACS.
fixes #286
=> Don't upload sigstore signatures

custom_components/spook/event.py
Allow ectoplasms to provide the new event entities.
Adding this will allow to add new event entities on top of existing integrations.
=> Add support for event entities in ectoplasms

custom_components/spook/ectoplasms/repairs/entity.py, custom_components/spook/ectoplasms/repairs/sensor.py, custom_components/spook/translations/en.json
Adds a new repair device and sensors.
Provides insights to current repairs.
Adding more entities in follow-up PRs.
=> Add repairs issue sensors

README.md, documentation/faq.md
Switch to SemVer for versioning of Spook.
Version numbers used to be random, but I guess it's time to grow up. The last version as v1.0.0, so now is the time to move forward with SemVer if I want.
Besides, all tools I use already assume it (so doing the random pattern was actually more work... 😬 )
=> Be a big boy, switch to SemVer

documentation/support.md
Corrected two instances of a missing u in the urls to get to the GitHub discussions. 
Without this change the urls are broken.
I clicked the links. Thoroughly.
=> Update support pages to correct discussion URLs

custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
Fixes an bug introduced while fixing #318 
fixes #324
=> Fix unknown entity references for badge objects in dashboards

documentation/myst.yml
=> Fix documentation site title

documentation/features.md
Add helpers section to the features documentation.
This was missed in the original docs PR.
=> Add helpers to features documentation

documentation/services.md
Add the new person services added in the previous release to the services index.
Forgot to do that 😓
=> Add person services to service index

custom_components/spook/services.yaml
`s/spookes/spooks` and the comma is not necessary
Fixes a typo
n/a
n/a
=> Fix typo for `Boo!` service

custom_components/spook/ectoplasms/homeassistant/services/disable_device.py, custom_components/spook/ectoplasms/homeassistant/services/enable_device.py
Fixes accepting lists of devices in the device enable & disable services.
This was already documented, but wasn't actually working.
Thanks @TheFes for reaching out about this.
=> Fix accepting list of devices in enable/disable service

custom_components/spook/ectoplasms/homeassistant/services/disable_config_entry.py, custom_components/spook/ectoplasms/homeassistant/services/enable_config_entry.py, documentation/integrations.md
As pointed out / requested by @TheFes, also allow multiple config entries in a single service call to disable/enable them.
=> Allow enabling/disable multiple config entries in a single call

custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
=> Skip device IDs that are empty strings

custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
=> Skip scene inspection is data platform is missing

documentation/media.md
=> Add Spook's mention in the Self-Hosted podcast

documentation/media.md
Adds a YouTube video from Gryd about Spook
https://www.youtube.com/watch?v=fgXF2L1Vy0Q
=> Add video about Spook from Gryd

documentation/media.md
=> Fix embedded video in the docs

custom_components/spook/__init__.py, custom_components/spook/util.py
Add support for forwarding the config entry setup to ecoplasms.
=> Add support for forwarding entry setup to Ectoplasms

custom_components/spook/ectoplasms/homeassistant/templating/type_debug.py, custom_components/spook/ectoplasms/homeassistant/templating/typeof.py
Adds a method to debug the type of a variable/value.
This can be helpful when juggling with templates in the template editor in the developer tools to figure out what you've got.
```
{{ typeof("what is this") }}  # "str"
{{ typeof(["a", "b"]) }} # "list"
{{ "and this?" | typeof }} # "str"
```
It is not possible to figure out the type of value currently, which can be helpful at times.
=> Add template method: typeof

poetry.lock, pyproject.toml
To prevent resolving issues a shown in #528
=> Adjust supported Python version range

.github/LICENSE.md, README.md, documentation/license.md
=> :fireworks: Updates maintenance/license year to 2024

custom_components/spook/ectoplasms/cloud/switch.py, custom_components/spook/ectoplasms/homeassistant/button.py, custom_components/spook/ectoplasms/homeassistant/sensor.py, custom_components/spook/ectoplasms/repairs/button.py, custom_components/spook/ectoplasms/repairs/sensor.py
Modernizes the entity description a bit more, to follow development in Core.
=> Modernize sensor entity descriptions

custom_components/spook/ectoplasms/group/repairs/unknown_members.py
Fixes the change detection on groups.
Right now, if a group has a repair open and the user changes the group to fix the issue, it ain't detected. This PR fixes that issue.
fixes #533
=> Fix detecting changes to groups

custom_components/spook/ectoplasms/cloud/switch.py, custom_components/spook/ectoplasms/homeassistant/button.py, custom_components/spook/ectoplasms/homeassistant/sensor.py, custom_components/spook/ectoplasms/repairs/button.py, custom_components/spook/ectoplasms/repairs/sensor.py
Don't freeze entity descriptions, for backward-compatibility with older Home Assistant versions.
=> Do not freeze entity descriptions for backward-compatibility

custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/group/repairs/unknown_members.py, custom_components/spook/ectoplasms/integration/repairs/unknown_source.py, custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py
This PR cleans up possible open repairs from entities that do no longer exists.
For example, if an automation has an unreferenced entity, one way to fix the issue is to delete the whole automation. This PR ensures the repairs is also cleaned up in those cases.
=> Clean up repairs created for no longer existing entities

custom_components/spook/ectoplasms/homeassistant/templating/md5.py
Add a very simple small method: md5 to create MD5 hashes.
Mostly just because we can. It may be helpful for some random value or something.
=> Add template method: md5

custom_components/spook/ectoplasms/homeassistant/templating/sha1.py
Mostly a just because we can type of PR. A method to create sha1 hashes.
=> Add template method: sha1

custom_components/spook/ectoplasms/homeassistant/templating/sha256.py
This is mostly: because we can. A method to create sha256 hashes.
=> Add template method: sha256

custom_components/spook/ectoplasms/utility_meter/__init__.py, custom_components/spook/ectoplasms/utility_meter/repairs/__init__.py, custom_components/spook/ectoplasms/utility_meter/repairs/unknown_source.py, custom_components/spook/translations/en.json, documentation/_toc.yml, documentation/enhanced_integrations.md, documentation/integrations/utility_meter.md
Detects unknown sources of utility meters and raises a repair for them.
=> Detect unknown source used in utility meter helpers

custom_components/spook/ectoplasms/trend/__init__.py, custom_components/spook/ectoplasms/trend/repairs/__init__.py, custom_components/spook/ectoplasms/trend/repairs/unknown_source.py, custom_components/spook/translations/en.json, documentation/_toc.yml, documentation/enhanced_integrations.md, documentation/integrations/trend.md
Detect the use of unknown source entities in trend helpers.
=> Detect unknown source used in trend helpers

custom_components/spook/manifest.json
Should fix the occurrence in https://github.com/frenck/spook/discussions/562
=> Ensure timer is set up before adding services

custom_components/spook/ectoplasms/proximity/__init__.py, custom_components/spook/ectoplasms/proximity/repairs/__init__.py, custom_components/spook/ectoplasms/proximity/repairs/unknown_ignored_zones.py, custom_components/spook/ectoplasms/proximity/repairs/unknown_tracked_entities.py, custom_components/spook/ectoplasms/proximity/repairs/unknown_zone.py, custom_components/spook/manifest.json, custom_components/spook/translations/en.json, documentation/_toc.yml, documentation/enhanced_integrations.md, documentation/glossary.md, documentation/installation.md, documentation/integrations/proximity.md
Added repair inspections for the new proximity shipped in Home Assistant 2024.2.
Find and detects tracking of unknown entities.
Needs: #595
Good. See the screenshot down below.
=> Add inspections for proximity issues

documentation/integrations/proximity.md
SSIA.
The frontmatter had an error on the new proximity documentation page.
=> Fix rendering of proximity documentation page

custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py, custom_components/spook/ectoplasms/group/repairs/unknown_members.py, custom_components/spook/ectoplasms/integration/repairs/unknown_source.py, custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/proximity/repairs/unknown_ignored_zones.py, custom_components/spook/ectoplasms/proximity/repairs/unknown_tracked_entities.py, custom_components/spook/ectoplasms/proximity/repairs/unknown_zone.py, custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py, custom_components/spook/ectoplasms/trend/repairs/unknown_source.py, custom_components/spook/ectoplasms/utility_meter/repairs/unknown_source.py, custom_components/spook/util.py
Refactoring the filtering/getting of entities/devices/areas and services.
Less duplication, smaller repairs implementations
=> Refactor getting/filtering for unknown entity/area/devices/services

custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py, custom_components/spook/ectoplasms/integration/repairs/unknown_source.py, custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py, custom_components/spook/repairs.py
This PR fixes the auto cleanup of issues.
This is a regression of cleanup done in [v2.2.1](https://github.com/frenck/spook/releases/tag/v2.2.1), more specifically in #603.
- fixes #623
- fixes #620
- fixes #626
- fixes #624
- fixes #650
- fixes #636
=> Fix auto-cleanup of repair issues

custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py, custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py, custom_components/spook/ectoplasms/group/repairs/unknown_members.py, custom_components/spook/ectoplasms/proximity/repairs/unknown_ignored_zones.py, custom_components/spook/ectoplasms/proximity/repairs/unknown_tracked_entities.py, custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
Performance improvements based on part of the profile shown by @bdraco in this comment:
https://github.com/frenck/spook/issues/618#issuecomment-2016764699
=> Performance improvements

documentation/media.md
Add a couple of new mentions/videos about Spook I've found.
=> Add mentions of Spook in media

documentation/index.md
=> Some more doc tweaks

hacs.json, pyproject.toml, requirements-dev.lock, requirements.lock
Require at least Home Assistant 2024.4.0 for Spook (beta version will do).
In prep for adding floor/label stuff.
=> Require at least Home Assistant 2024.4.0

.github/renovate.json
SSIA, left over after removing Poetry.
=> Clean up Poetry from Renovate configuration

custom_components/spook/ectoplasms/automation/repairs/unknown_floor_references.py, custom_components/spook/translations/en.json, custom_components/spook/util.py
SSIA, detect the use of unknown targeted floors in automations.
=> Detect unknown floors used in automations

custom_components/spook/ectoplasms/script/repairs/unknown_label_references.py, custom_components/spook/translations/en.json
SSIA, find non-existing labels that are targeted in scripts.
=> Detect unknown labels used in scripts

custom_components/spook/ectoplasms/homeassistant/services/create_floor.py, custom_components/spook/services.yaml
Adds a service to create floors: `homeassistant.create_floor`.
=> Add homeassistant.create_floor service

custom_components/spook/ectoplasms/homeassistant/services/remove_alias_from_floor.py, custom_components/spook/services.yaml
SSIA, adds a service to remove an alias from a floor: `homeassistant.remove_alias_from_floor`
=> Add homeassistant.remove_alias_from_floor service

custom_components/spook/ectoplasms/homeassistant/services/delete_floor.py, custom_components/spook/services.yaml
SSIA, adds a service to delete a floor.
=> Add homeassistant.delete_floor service

custom_components/spook/util.py
SSIA, fixes a small bug that caused an stacktrace
=> Fix gathering of all floor IDs

custom_components/spook/ectoplasms/homeassistant/services/create_label.py, custom_components/spook/services.yaml
SSIA, adds a service to create Home Assistant labels on the fly.
=> Add homeassistant.create_label service

custom_components/spook/ectoplasms/homeassistant/services/add_label_to_device.py, custom_components/spook/services.yaml
SSIA, adds a service to assign labels to devices: `homeassistant.add_label_to_device`
=> Add homeassistant.add_label_to_device service

custom_components/spook/ectoplasms/homeassistant/services/remove_label_from_area.py, custom_components/spook/services.yaml
SSIA, adds a service to remove labels from areas. `homeassistant.remove_label_from_area` service.
=> Add homeassistant.remove_label_from_area service

custom_components/spook/ectoplasms/homeassistant/services/remove_label_from_device.py, custom_components/spook/services.yaml
SSIA, adds a service to remove labels from devices: `homeassistant.remove_label_from_device`
=> Add homeassistant.remove_label_from_device service

custom_components/spook/repairs.py, custom_components/spook/services.py, custom_components/spook/templating.py, custom_components/spook/util.py
Fix blocking I/O on event loop Spook does while importing modules.
fixes #681
=> Fix blocking I/O on event loop while importing modules

documentation/index.md
Tone down and turn around the introduction text on the homepage index.
=> Recommend Spook, instead of discourage the use

custom_components/spook/ectoplasms/homeassistant/services/add_alias_to_floor.py, custom_components/spook/ectoplasms/homeassistant/services/remove_label_from_area.py
=> Fix area and floor registry service calls

custom_components/spook/ectoplasms/homeassistant/sensor.py, custom_components/spook/repairs.py
SSIA. Required for `2024.05`.
--
=> Add EventType annotations

custom_components/spook/entity.py
As reported in Discord
`TypeError: cannot inherit frozen dataclass from a non-frozen one`
=> Fix frozen dataclass inherits from a non-frozen one

documentation/index.md
Minor grammar fix
I ❤️ correct spelling
n/a
n/a
=> Typo: a instead of an scary toolbox

LICENSE.md, README.md, documentation/license.md
=> :fireworks: Updates maintenance/license year to 2025

custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py, custom_components/spook/util.py, documentation/integrations/automation.md, documentation/integrations/script.md
=> Add support for detecting entity usage in Templates

custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py, custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py, custom_components/spook/util.py
=> Fix template variables warnings

custom_components/spook/translations/de.json, custom_components/spook/translations/lt.json, custom_components/spook/translations/tr.json, custom_components/spook/translations/zh_Hant.json
=> Fix broken language placeholders in some language strings

custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py, custom_components/spook/util.py
=> Fix picking up filenames as entities
