README.md
custom_components/spook/services.yaml
custom_components/spook/services/input_select_shuffle.py
custom_components/spook/services/input_select_sort.py

Adds a couple of non-persistent service calls for `input_number`.
- `input_number.shuffle`
- `input_number.sort`

Add input_number.shuffle & sort service

---

custom_components/spook/services.yaml

Fixes a mixup in the service description schema, causing the selector to mix things up.
fixes #25

Fix service description schema for number.increment & input_number.increment

---

README.md
custom_components/spook/repairs/group_unknown_members.py
custom_components/spook/translations/en.json

Adds a new repair: Unkown group members.
Works for any group. Old-style and new-style, and for both YAML and UI-created groups.

Add repairs: Unknown group members

---

README.md
custom_components/spook/repairs/integration_unknown_source.py
custom_components/spook/translations/en.json

New detection that finds missing source entities in integration helpers

Add repair: Find missing source in integration helpers

---

README.md
custom_components/spook/services.yaml
custom_components/spook/services/homeassistant_delete_area.py

Renames "remove" area to "delete". Delete is more affiliated with a destructive action, while removing can just be removing a marker or things like that.

Rename remove area to delete area

---

README.md
custom_components/spook/services.yaml
custom_components/spook/services/homeassistant_delete_all_orphaned_entities.py

Renames the `homeassistant.remove_all_orphaned_entities` to `homeassistant.delete_all_orphaned_entities`.
Delete better reflects the destructive nature.

Rename remove all orphaned entities service to delete

---

custom_components/spook/services/homeassistant_add_device_to_area.py
custom_components/spook/services/homeassistant_add_entity_to_area.py

Called an incorrect method, causing them always to fail.

Fix add device/entity to area

---

custom_components/spook/translations/pt-BR.json

Hello @frenck,
How do you plan on handling translation contributions to this component?
If you think it's feasible to receive these contributions, here's the inclusion of translations into Brazilian Portuguese (`pt-BR`) for review.
Thanks for the component, very cool!

Adds translations for `pt-BR`

---

custom_components/spook/repairs/automation_unknown_entity_references.py
custom_components/spook/repairs/script_unknown_entity_references.py

Fixes #17 for now.
The problem and solutions are somewhere else.
The question is: Where does this happen? Why are templates ending up here in the first place and why aren't the entities extracted from the template render in the first place?
For now, ignoring templates in Spook to at least aid with avoiding false positives.

Ignore Templates when detecting unused entities

---

.github/renovate.json
.github/workflows/pr-labels.yaml

- Fixes an incorrect failure with PRs from forked repositories
- Let Renovate run on its own schedule

Small adjustment to CI & Renovate config

---

custom_components/spook/services/input_number_decrement.py
custom_components/spook/services/input_number_increment.py
custom_components/spook/services/input_number_max.py
custom_components/spook/services/input_number_min.py
custom_components/spook/services/number_decrement.py
custom_components/spook/services/number_increment.py

For me the `input_number` services does not work, throwing this error:
```
2023-03-26 20:28:54.837 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2569077664] Error handling message: Unknown error (unknown_error) Simon from 192.168.0.169 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 647, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File …
```

Use async_set_value function instead

---

custom_components/spook/repairs/obsolete_platform_yaml_config.py

`aladdin_connect` and `scrap` platforms are no longer configured via YAML.
Currently deprecated and fully removed in Home Assistant 2023.4

Add aladdin_connect and scrape as known obsolete YAML

---

custom_components/spook/repairs/switch_as_x_unknown_source.py
custom_components/spook/translations/en.json

Adds a new repair handler that detects switch as X helper entities that point to an switch that no longer exists.

Add repair: Find missing source switches for switch_as_x helpers

---

custom_components/spook/repairs/group_unknown_members.py

Don't inspect group repairs if integration isn't loaded

---

custom_components/spook/repairs/automation_unknown_entity_references.py
custom_components/spook/repairs/group_unknown_members.py
custom_components/spook/repairs/lovelace_unknown_entity_references.py
custom_components/spook/repairs/script_unknown_entity_references.py

All repairs handling entity IDs now ignore entity IDs that have an invalid format.
This is suboptimal IMHO, but there are quite a bunch of "custom" weird use cases out there, I'm not going to support; as an example: Custom template format of a custom button card. Just ignore it.
fixes #71

Repairs: Ignore invalid entity IDs in all cases

---

custom_components/spook/ectoplasms/cloud/switch.py
custom_components/spook/ectoplasms/homeassistant/sensor.py
custom_components/spook/translations/de.json
custom_components/spook/translations/en.json
custom_components/spook/translations/nl.json

Add entity name translations to all entities.
Includes the translations for `en`, `nl` and `de`.

Add entity name translations to all entities

---

README.md
custom_components/spook/ectoplasms/homeassistant/services/restart.py
custom_components/spook/services.yaml

As requested here: <https://github.com/frenck/spook/discussions/6>

Extend Home Assistant restart service with an force option

---

custom_components/spook/binary_sensor.py
custom_components/spook/button.py
custom_components/spook/const.py
custom_components/spook/number.py
custom_components/spook/select.py
custom_components/spook/switch.py
custom_components/spook/time.py
custom_components/spook/util.py

Extract some duplicated logic from platforms, and adds basics for numbers, selects, binary sensors and time entities (added in future PRs).

Add util to forward platform entry setup to ectoplasm, add other future platforms

---

custom_components/spook/translations/de.json
custom_components/spook/translations/en.json
custom_components/spook/translations/es.json
custom_components/spook/translations/nl.json

Fixes
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1005
First occurred: 4:23:47 PM (1 occurrences)
Last logged: 4:23:47 PM
Entity sensor.custom_integrations (<class 'custom_components.spook.ectoplasms.homeassistant.sensor.HomeAssistantSpookSensorEntity'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
```

Fix incorrect translation key

---

custom_components/spook/ectoplasms/recorder/services/import_statistics.py

SSIA, name & unit of measurement should accept `None` in the validation (as it is their default as well).

Fix schema for recorder.import_statistics

---

.devcontainer/devcontainer.json
.gitignore
.vscode/launch.json
.vscode/tasks.json

Adds a dev container for Spook 👻 
Making it easier to develop on docs and Spook itself.
The container can surely be improved and more polished, but the basics work.
closes #265
- Open in devcontainer in VSCode, hitted F5 to run Home Assistant.
- Tested to run the documentation task to view the website.

Add devcontainer

---

documentation/installation.md

The documentation listed 2023.7.0 as the minimal version; however, this is actually 2023.8.0.

Fix minimal Home Assistant version in docs

---

custom_components/spook/services.py

Add support to the framework for handling services that respond with data.
I did notice some weirdness, like: It seems like Home Assistant doesn't support this concept for admin services (likely a miss, but I don't see the use case at this point either).
So we can add some awesome services.
I didn't.

Add support for service responses

---

custom_components/spook/const.py
custom_components/spook/ectoplasms/repairs/event.py
custom_components/spook/translations/en.json

Adds an event entity for Home Assistant Repairs
This entity allows you to monitor if new repairs are raised (or existing ones changed/removed).
It can help create notifications.
The attributes contain the integration that issued the issue and the issue ID.
The plan is to create a service to query the issue registry to get the details on it.

Add event entity for Home Assistant Repairs

---

custom_components/spook/ectoplasms/repairs/button.py
custom_components/spook/translations/en.json

Adds buttons for (un)ignoring all repair issues
See recording below.

Add button entities for ignoring / unignoring repairs

---

custom_components/spook/ectoplasms/cloud/switch.py
custom_components/spook/ectoplasms/homeassistant/button.py
custom_components/spook/ectoplasms/homeassistant/sensor.py
custom_components/spook/ectoplasms/repairs/button.py
custom_components/spook/ectoplasms/repairs/sensor.py

SSIA, the thing has moved in Home Assistant. Since Spook now required 2023.8.0, is is save to correct the location.

Fix import location of EntityCategory

---

custom_components/spook/ectoplasms/zone/__init__.py
custom_components/spook/ectoplasms/zone/services/__init__.py
custom_components/spook/ectoplasms/zone/services/create.py
custom_components/spook/ectoplasms/zone/services/delete.py
custom_components/spook/ectoplasms/zone/services/update.py
custom_components/spook/manifest.json
custom_components/spook/services.yaml

Add support for creating/updating/deleting zones using services.
Was requested here: <https://github.com/frenck/spook/discussions/155>
One could create dynamic or moving zones using automations.
Good!

Add services to add/update/delete zones

---

custom_components/spook/ectoplasms/zone/services/create.py
custom_components/spook/ectoplasms/zone/services/delete.py
custom_components/spook/ectoplasms/zone/services/update.py

Adds a workaround to get to the Zone storage collection.
Home Assistant doesn't set the Zone storage collection into the hass.data when the Home zone is defined/overriden in YAML. Causing Spook his zone services to fail.
This PR adds a workaround by grabbing the collection from the WebSocket API handlers. (Super dirty).
fixes #311 
Defined the Home zone in YAML and restarted HA. 
Confirmed the services now work, but don't work without the PR applied.
-

Fix zone services not working with YAML home zone

---

custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py

The entities shown in badges of dashboards can be filtered. This wasn't handled by Spook when looking for unknown entity rereferences.
fixes #318
Good.

Fix unknown dashboard entities repair for filtered badges

---

custom_components/spook/ectoplasms/repairs/event.py

Fixes
```
Entity event.repair (<class 'custom_components.spook.ectoplasms.repairs.event.RepairsSpookEventEntity'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.
```
fixes #312
Run, confirmed it is gone.

Fix implicit use of device name in Repairs event

---

custom_components/spook/__init__.py
custom_components/spook/config_flow.py
custom_components/spook/integrations/__init__.py
custom_components/spook/repairs.py
custom_components/spook/translations/en.json
custom_components/spook/util.py

This adds support for shipping integrations from within Spook itself.
Spook has much to offer and could be offering much more. However, the concept of integration in Home Assistant is limited to a single integration at a time.
Trying to break that barrier with Spook, by having Spook smuggle multiple integrations inside itself like a little trojan horse.
The goal is to be able to provide additional other integrations, like, for example, new helpers.
It hasn't yet, this is building the foundation.

Add support for sub-integrations

---

custom_components/spook/ectoplasms/person/__init__.py
custom_components/spook/ectoplasms/person/services/__init__.py
custom_components/spook/ectoplasms/person/services/add_device_tracker.py
custom_components/spook/ectoplasms/person/services/remove_device_tracker.py
custom_components/spook/manifest.json
custom_components/spook/services.yaml

Adds services to modify persons in Home Assistant, allowing to add/remove devices trackers from them on the fly.
As requested in: https://github.com/frenck/spook/discussions/325
It would, for example, allow temporarily attaching a device tracker (for example, a car tracker) to a person while they are traveling.
Using the dev tools

Add services to add/remove device trackers from persons

---

custom_components/spook/integrations/spook_inverse/translations/en.json

Spook should always identify itself; however, it did not on the "Add helper" dialog. This PR fixes that.

Fix display of inverse helper

---

custom_components/spook/ectoplasms/scene/__init__.py
custom_components/spook/ectoplasms/scene/repairs/__init__.py
custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
custom_components/spook/translations/en.json

Add logic to raise repairs for scenes that have unknown entity references.
Referencing non-existing entities in scene, may cause your scene not to work as expected.
These issues are hard to pinpoint, Spook helps with this one.

Raise repairs for unknown entity references in scenes

---

custom_components/spook/repairs.py

Thanks to a Tweet JLo sent out, I learned that the cooldown period of Spook was rather generous.
This PR reduces it from 10 seconds to 3 seconds.
This will help Spook to respond faster on changes happening on the system. 10 second is quite a bit, and big enough to notice / be annoying.

Reduce repair event debounce cooldown period to 3 seconds

---

custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py

Change a LOGGER.error statement that's not used to log an error to a more approproate debug statement.
I new errors in my HA log after installing spook, and after I'd fixed all the repairs. Since the error's title was just `Scene: scene.one_of_my_scenes`, repeated multiple times for each scene, I checked the code and noticed that every time a scene's entities are scanned for missing entities (e.g. when saving a scene), the scene's id is logged as error. This PR changes the message's log level to debug.
1. changed the file locally
2. deleted the corresponding pycache file
3. restarted HomeAssistant
4. changed a scene, to see if the log's gone
5. error is no longer logged!
6. reverted the change locally, then repeated 2.-4. to check that the error comes back, which it does

Don't use LOGGER.error for debug logging during scene entities check

---

custom_components/spook/ectoplasms/homeassistant/services/restart.py
custom_components/spook/services.yaml

This adds support for restarting Home Assistant in safe mode. This is added in Home Assistant 2023.11, and because of this addition, the restart service currently breaks when using Spook.
Fix it!
Good!
Shot the screen, now has a bullet hole.

Add Home Assistant restart safe_mode support

---

custom_components/spook/ectoplasms/homeassistant/sensor.py

The following error occurs:
```
2023-10-25 22:02:45.618 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up spook platform for sensor
Traceback (most recent call last):
File "/home/frenck/code/home-assistant/core/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
await asyncio.shield(task)
File "/home/frenck/code/home-assistant/core/config/custom_components/spook/sensor.py", line 22, in async_setup_entry
await async_forward_platform_entry_setups_to_ectoplasm(
File "/home/frenck/code/home-assistant/core/config/custom_components/spook/util.py", line 32, in async_forward_platform_entry_setups_to_ectoplasm
module = importlib.import_module(f".{module_path}", __package__)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

Fix no attribute EVENT_PERSISTENT_NOTIFICATIONS_UPDATED

---

documentation/integrations/automation.md
documentation/integrations/script.md

Added the word "not" to limitation
Documentation had a typo
Looked at the markdown on GitHub

Fixed typo in automation integration documentation

---

custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py
custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py
custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py

When an automation or script has an parsing error, and entity stub object is used to fill in the gap. Being `UnavailableScriptEntity` and `UnavailableAutomationEntity`.
These can be skipped for determining unknown entities/devices/areas, as they are not valid YAML/not loaded.
Fixes #476
Good

Fix crash on unavailable automations & scripts

---

documentation/installation.md
hacs.json

To support error translations and the new `ServiceValidationError`, Spook is bumping the minimal required version of Home Assistant to 2023.12.0

Bump min required Home Assistant to 2023.12.0

---

custom_components/spook/__init__.py
custom_components/spook/templating.py
custom_components/spook/util.py

Add support for extending the Home Assistant template engine.
It would be cool if Spook could extend the Home Assistant template engine with custom functions/tests.
`fnmatch` is not an existing template method in Home Assistant, but injected by Spook.

Add possibility to extend the Home Assistant template engine

---

custom_components/spook/ectoplasms/homeassistant/templating/__init__.py
custom_components/spook/ectoplasms/homeassistant/templating/shuffle.py

Adds a template method to shuffle lists.
Shuffling lists, is currently way to complex.
See for example: https://community.home-assistant.io/t/get-randrom-value-which-not-duplicate-with-the-value-in-previous-random-list/393887
See screenshot down below

Add template method: shuffle

---

custom_components/spook/ectoplasms/homeassistant/templating/fnmatch_filter.py

Add the `fnmatch_filter` template method, allowing to use Unix filename pattern matching to filter a list of strings.
This provides an easier way/alternative to the regex versions that Home Assistant core has.
One could, for example:
```
{{ fnmatch_filter(["test", "test2", "no-test", "no-pain", "no-glory"], "t*") }}
{{ fnmatch_filter(["test", "test2", "no-test", "no-pain", "no-glory"], "no-*") }}
```

Add template method: fnmatch_filter

---

custom_components/spook/ectoplasms/homeassistant/templating/fnmatch.py

Add the `fnmatch` template method, allowing to use Unix filename pattern matching on strings or lists of strings. 
This provides an easier way/alternative to the regex versions that Home Assistant core has.
On could, for example:
```
{{ fnmatch("test", "t*") }}  # True
{{ fnmatch("notest", "t*") }}  # False
{{ fnmatch(["test", "test2"], "t*") }}  # True
{{ fnmatch(["test", "test2", "no-test"], "t*") }}  # False
```
With the examples above.

Add template method: fnmatch

---

custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/group/repairs/unknown_members.py
custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py
custom_components/spook/repairs.py

Some repairs listen for config entry changes. This PR refactors that code a little bit, to remove a bit of de-duplication.

Add option to listen for config entry changes to trigger repair

---

custom_components/spook/ectoplasms/homeassistant/templating/sha512.py

Mostly because we can... it is a more comment checksum method nowadays, so it might have some use.

Add template method: sha512

---

custom_components/spook/templating.py

Allow template methods to have slighter different names when used as a filter or test.

Allow template method to be named different for tests and filters

---

custom_components/spook/ectoplasms/homeassistant/templating/flatten.py

Add support for flatten. It can flatten nested lists.
Because it is nasty hard to do in Jinja

Add template method: flatten

---

hacs.json

Bumps the minimal required Home Assistant version to be 2024.2.0 and HACS 1.34.0.
The Home Assistant bump is needed for upcoming detections for Promixity, which has been overhauled in 2024.2.
The HACS bump is to aid/help with getting people bumped to prevent issues with an distribution issue in earlier HACS versions.
It has not been tested. This is Spook, not your homie.

Bump min req Home Assistant 2024.2.0 and HACS 1.34.0

---

custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py
custom_components/spook/translations/en.json
documentation/integrations/automation.md

Adds a new inspection to Spook, that can find done service calls in automations and thus able to report on when unknown service calls are made.
Calling non-existing services cause errors and might go undetected. This allows Spook to be proactive and warn before use / run of the actual service.
This inspection will need refactoring in the future, as parts of this one are re-usable (e.g., for scripts).
By making the worst automations possible.

Add inspections for unknown service calls in automations

---

custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py
custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py
custom_components/spook/ectoplasms/group/repairs/unknown_members.py
custom_components/spook/ectoplasms/integration/repairs/unknown_source.py
custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/proximity/repairs/unknown_ignored_zones.py
custom_components/spook/ectoplasms/proximity/repairs/unknown_tracked_entities.py
custom_components/spook/ectoplasms/proximity/repairs/unknown_zone.py
custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py
custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py
custom_components/spook/ectoplasms/trend/repairs/unknown_source.py
custom_components/spook/ectoplasms/utility_meter/repairs/unknown_source.py
custom_components/spook/repairs.py

SSIA
Refactor of the repair issue handling, so Spook is now handling the cleanup of them in the abstract instead of each repair individually.
uh... well.. less is more?

Deduplicate repair issue cleanup code

---

custom_components/spook/util.py

Fixes a bug reported by @Mariusthvdb on the Home Assistant Community forums.
```
Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7fcc85ea3560>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
await task
File "/config/custom_components/spook/repairs.py", line 134, in _async_inspect
await self.async_inspect()
File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 67, in async_inspect
_async_find_services_in_sequence(
File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 136, in _async_find_services_in_sequence …
```

Fix parsing of used services when encountering a repeat action

---

custom_components/spook/util.py

Back in the Home Assistant days, services could be called in different ways. Using the `service` key and using the `service_template` key. The latter supported templates, the first didn't in the past (but now does).
`service_template` isn't used anymore (but Home Assistant is still backwards compatible).
This PR makes sure Spook has the same backward-compatibility.
fixes #615

Fix detecting service calls that use old-style service_template

---

custom_components/spook/ectoplasms/cloud/switch.py

Make the `_update_state`  function of the cloud switch entities a coro.
The `async_listen_updates` of the cloud client requires the function to be a coro, as the function uses the `async_create_catching_coro` logging helper of core, which (in some nested functions) always awaits.
This appeared while beta testing https://github.com/home-assistant/core/issues/111797.
I applied this change on my prod system and the log went away.

Make cloud switch entity `_update_state` function a coro

---

custom_components/spook/repairs.py

Fixes upcoming breaking change in 2024.4 as referenced in #665 and https://github.com/home-assistant/core/pull/113798#issue-2194328239
This change makes it backward compatible with previous releases by checking type of event param
Solves breaking change in 2024.4
Motivation - I had to fix this myself in Battery Notes so sharing as Spook has been great inspiration for me starting out creating custom components.
Tested against current releases prior to 2024.4 only
fixes #665

Fix for event filter

---

custom_components/spook/util.py

Fixes a regression from #606, which caused us no longer skip empty device IDs.
fixes #619 
While empty device ID are, actually, not good. They are accepted by Home Assistant (and abused in Blueprints quite a bit). Therefore, skipping makes sense to prevent bunch of bug report 🙄

Fix detecting empty device IDs

---

custom_components/spook/ectoplasms/automation/repairs/unknown_label_references.py
custom_components/spook/translations/en.json
custom_components/spook/util.py

SSIA, detects the use of unknown labels in automations and raises repairs for it.

Detect unknown labels used in automations

---

custom_components/spook/ectoplasms/script/repairs/unknown_floor_references.py
custom_components/spook/translations/en.json

SSIA, detects targeting of unknown floors in scripts and created a repair for them.

Detect unknown floors used in scripts

---

custom_components/spook/ectoplasms/homeassistant/services/create_area.py
custom_components/spook/services.yaml

Areas now support icons, this adds support for it to the `homeassistant.create_area` service call.

Allow setting icon on homeassistant.create_area service

---

custom_components/spook/ectoplasms/homeassistant/services/add_alias_to_floor.py
custom_components/spook/services.yaml

SSIA, allows to add an alias to a floor on the fly: `homeassistant.add_alias_to_floor`

Add homeassistant.add_alias_to_floor service

---

custom_components/spook/ectoplasms/homeassistant/services/set_floor_aliases.py
custom_components/spook/services.yaml

SSIA, adds a service that allows to replace aliases of a floor (the complete set): `homeassistant.set_floor_aliases`

Add homeassistant.set_floor_aliases service

---

custom_components/spook/ectoplasms/homeassistant/services/add_area_to_floor.py
custom_components/spook/services.yaml

SSIA, adds a service that can assign an area to a floor: `homeassistant.add_area_to_floor`

Add homeassistant.add_area_to_floor service

---

custom_components/spook/ectoplasms/homeassistant/services/remove_area_from_floor.py
custom_components/spook/services.yaml

SSIA, adds a service to remove an area from a floor.
Since an area can only be in a single floor at a time, there is no need to ask for floor input. This service simply clear the floor from the selected area.

Add homeassistant.remove_area_from_floor service

---

custom_components/spook/services.yaml

Use floor selector in floor related services

---

custom_components/spook/ectoplasms/homeassistant/services/delete_label.py
custom_components/spook/services.yaml

SSIA, adds a service to Home Assistant that can delete a label.

Add homeassistant.delete_label service

---

custom_components/spook/ectoplasms/homeassistant/services/add_label_to_area.py
custom_components/spook/services.yaml

Adds a service that can assign labels to areas: `homeassistant.add_label_to_area`.

Add homeassistant.add_label_to_area service

---

custom_components/spook/ectoplasms/homeassistant/services/add_label_to_entity.py
custom_components/spook/services.yaml

SSIA, adds a service to assign labels to entities: `homeassistant.add_label_to_entity`.

Add homeassistant.add_label_to_entity service

---

custom_components/spook/ectoplasms/homeassistant/services/remove_label_from_entity.py
custom_components/spook/services.yaml

SSIA, adds an service to remove labels from entities: `homeassistant.remove_label_from_entity`.

Add homeassistant.remove_label_from_entity service

---

documentation/installation.md
hacs.json
pyproject.toml
requirements-dev.lock
requirements.lock

Same as #692, however, Home Assistant 2024.4.0 is now stable. Thus locking the version down correctly now.

Require at least Home Assistant 2024.4.0

---

documentation/integrations/recorder.md

Changed YAML example to show stats list as required by recorder statistics service and change source to recorder (as calls with source other than "recorder" were rejected)
Existing YAML example doesn't show the stats in the list format required by the service.
I found an example in this discussion https://github.com/frenck/spook/discussions/19 and tested using this format.
I have loaded 16 months worth of hourly history for Battery Import, Export, Grid Import and Export, and Solar production, and verified that these load correctly.

Update recorder.md to improve YAML example.

---

custom_components/spook/__init__.py
custom_components/spook/config_flow.py
custom_components/spook/ectoplasms/homeassistant/entity.py
custom_components/spook/ectoplasms/homeassistant/templating/flatten.py
custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
custom_components/spook/ectoplasms/recorder/services/import_statistics.py
custom_components/spook/ectoplasms/repairs/button.py
custom_components/spook/ectoplasms/repairs/entity.py
custom_components/spook/ectoplasms/repairs/event.py
custom_components/spook/ectoplasms/timer/services/set_duration.py
custom_components/spook/ectoplasms/zone/services/delete.py
custom_components/spook/ectoplasms/zone/services/update.py
custom_components/spook/integrations/spook_inverse/entity.py
custom_components/spook/repairs.py
custom_components/spook/services.py
custom_components/spook/templating.py
custom_components/spook/util.py

Misc typing improvements

---

custom_components/spook/ectoplasms/cloud/entity.py
custom_components/spook/ectoplasms/cloud/switch.py
custom_components/spook/ectoplasms/homeassistant/button.py
custom_components/spook/ectoplasms/homeassistant/sensor.py
custom_components/spook/ectoplasms/repairs/button.py
custom_components/spook/ectoplasms/repairs/event.py
custom_components/spook/ectoplasms/repairs/sensor.py

SSIA
Improve typing and fix some issues.
--

Change Description dataclasses to frozen

---

custom_components/spook/ectoplasms/input_number/services/decrement.py
custom_components/spook/ectoplasms/input_number/services/increment.py
custom_components/spook/ectoplasms/number/services/decrement.py
custom_components/spook/ectoplasms/number/services/increment.py

Updates increment and decrement services in Spook to handle floating-point arithmetic inaccuracies.
- Replaces the strict equality check for step multiples with a tolerance-based check using `math.isclose` in `custom_components/spook/ectoplasms/number/services/decrement.py` and `increment.py`. This change addresses the issue of floating-point arithmetic inaccuracies when checking if an amount is a multiple of the step value.
- Applies the same tolerance-based check for step multiples in `custom_components/spook/ectoplasms/input_number/services/decrement.py` and `increment.py`, ensuring consistency across different types of number entities within Spook.
fixes #744
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/frenck/spook?shareId=d62737e …

Fix decimal math inaccuracy in increment/decrement services

---

custom_components/spook/integrations/spook_inverse/manifest.json
custom_components/spook/manifest.json

Removes the platinum scale marker, as those currently cause hassfest to fail.
They are fake (as this is really not a platinum level integration) and not used anyways. So nothing changes.

Remove platinum quality scale markers (they where fake anyways)

---

custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py

Search for unknown entity inside sections
Sections were not included in search.

Search for unknown entities inside sections

---

documentation/core_extensions.md

The Devices & Entities' _Learn More_ link currently links to the Device Management page

Fix link from Core Extensions to Devices & Entities
